In [1]:
import pandas as pd
data = {
    "name": ["John", "Ted", "Dev", "Brad", "Rex", "Smith", "Samuel", "David"],
    "salary": [10000, 20000, 50000, 45500, 19800, 95000, 5000, 50000],
    "management": [1, 0, 1, 0, 1, 0, 1, 0]}

# create dataframe from data dictionary
df = pd.DataFrame(data) # print the dataframe display(df.head())
df

name  salary  management
0    John   10000           1
1     Ted   20000           0
2     Dev   50000           1
3    Brad   45500           0
4     Rex   19800           1
5   Smith   95000           0
6  Samuel    5000           1
7   David   50000           0

In [2]:
for index, row in df.iterrows():
    print(f"{index},{row['name']},{row['salary']},{row['management']}")

0,John,10000,1
1,Ted,20000,0
2,Dev,50000,1
3,Brad,45500,0
4,Rex,19800,1
5,Smith,95000,0
6,Samuel,5000,1
7,David,50000,0


In [3]:
# import projtool as pt

df_prompt_data = pd.read_csv("./data/prompt_log.csv")
df_prompt_data

date prompt_component  version  class  \
0   2024-02-26          context        1      2   
1   2024-02-26    prompt_prefix        1      0   
2   2024-02-26    prompt_prefix        1      1   
3   2024-02-27          context        2      2   
4   2024-02-27    prompt_prefix        2      0   
5   2024-02-27    prompt_prefix        2      1   
6   2024-02-29          context        3      2   
7   2024-02-29    prompt_prefix        3      0   
8   2024-02-29    prompt_prefix        3      1   
9   2024-03-23          context        4      0   
10  2024-03-23          context        4      1   
11  2024-03-23    prompt_prefix        4      0   
12  2024-03-23    prompt_prefix        4      1   
13  2024-03-28          context        5      0   
14  2024-03-28          context        5      1   
15  2024-03-28    prompt_prefix        5      0   
16  2024-03-28    prompt_prefix        5      1   

                                              content  \
0   You are a fiction writer who has observed a di...   
1   Write me a tweet similar to this one, under 14...   
2   Write me a tweet similar to this one, under 14...   
3   You are a fiction writer who has observed a di...   
4   Write me a tweet similar to this one, under 14...   
5   Write me a tweet similar to this one, under 14...   
6   You are a fiction writer who has observed a di...   
7   Write me a tweet similar to this one, under 14...   
8   Write me a tweet similar to this one, under 14...   
9   You are social commentator who enjoys diverse ...   
10  You are a world class reporter who has observe...   
11  Write me a tweet similar to this one, under 14...   
12  Write me a tweet similar to this one, under 14...   
13  You are social commentator who enjoys diverse ...   
14  You are a world class reporter who has observe...   
15  Write me a tweet similar to this one in length...   
16  Write me a tweet similar to this one in length...   

                                                notes  
0   initial context for both classes used for send...  
1        initial class 0 prompt used in web interface  
2        initial class 1 prompt used in web interface  
3                                   same as version 1  
4   avoid having to expand contractions on generat...  
5   avoid having to expand contractions on generat...  
6                                   same as version 2  
7              fix issue with generated tweet quoting  
8              fix issue with generated tweet quoting  
9            add context for class 0 generated tweets  
10                  change fiction writer to reporter  
11  remove contraction constraint, add similar fee...  
12                      remove contraction constraint  
13                                  same as version 4  
14                                  same as version 4  
15                   add similar length specification  
16                   add similar length specification

In [4]:
max_context_date = df_prompt_data.loc[df_prompt_data['prompt_component'] == 'context', 'date'].max()
max_prefix_c0_date = df_prompt_data.loc[(df_prompt_data['prompt_component'] == 'prompt_prefix') & \
                                        (df_prompt_data['class'] == 0), 'date'].max()
max_prefix_c1_date = df_prompt_data.loc[(df_prompt_data['prompt_component'] == 'prompt_prefix') & \
                                        (df_prompt_data['class'] == 1), 'date'].max()
print(max_context_date, max_prefix_c0_date, max_prefix_c1_date)

max_context = df_prompt_data.loc[(df_prompt_data['prompt_component'] == 'context') & \
                                 (df_prompt_data['date'] == max_context_date), 'content'].values[0]
print(max_context)


2024-03-28 2024-03-28 2024-03-28
You are social commentator who enjoys diverse opinions and likes to tweet.


In [5]:
pd.set_option('display.max_colwidth', None)

In [6]:
import projtools as pt

indices_dict = pt.get_batch_indices()
print(indices_dict)
print()

df_consolidated = pt.consolidate_tweet_batches(indices_dict)
print(df_consolidated.shape)
df_consolidated.head()
# context0 = "You are social commentator who enjoys diverse opinions and likes to tweet."
# context1 = "You are a world class reporter who has observed a disaster and likes to tweet."
# prompt0 = "Write me a tweet similar to this one in length and content, under 141 characters, does not contain double quotes, but refers to a different activity, feeling and location: "
# prompt1 = "Write me a tweet similar to this one in length and content, under 141 characters, does not contain double quotes, but refers to a different disaster and location: "
# class0_tweets_test = pt.generate_tweet_batch(class_label=0, context_by_class=context0, start_prompt_by_class=prompt0, batch_start=400, batch_end=599)
# class1_tweets_test = pt.generate_tweet_batch(class_label=1, context_by_class=context1, start_prompt_by_class=prompt1, batch_start=400, batch_end=599)

{'tweet_batches_class0': [(0, 199), (200, 399), (400, 599), (600, 799), (800, 999), (1000, 1199), (1200, 1399), (1400, 1599), (1600, 1799), (1800, 1999), (2000, 2199), (2200, 2399), (2400, 2599), (2600, 2799), (2800, 2999), (3000, 3199), (3200, 3399), (3400, 3599), (3600, 3799), (3800, 3999), (4000, 4199), (4200, 4297)], 'tweet_batches_class1': [(0, 199), (200, 399), (400, 599), (600, 799), (800, 999), (1000, 1199), (1200, 1399), (1400, 1599), (1600, 1799), (1800, 1999), (2000, 2199), (2200, 2399), (2400, 2599), (2600, 2799), (2800, 2999), (3000, 3189)]}

First tweet file for class 0: ./data/prompts_v05/aug_tweets_class0_v05prompt_0000_0199.csv
Processessing file: ./data/prompts_v05/aug_tweets_class0_v05prompt_0200_0399.csv
Processessing file: ./data/prompts_v05/aug_tweets_class0_v05prompt_0400_0599.csv
Processessing file: ./data/prompts_v05/aug_tweets_class0_v05prompt_0600_0799.csv
Processessing file: ./data/prompts_v05/aug_tweets_class0_v05prompt_0800_0999.csv
Processessing file: ./d

text  \
id                                                                                                                                                                               
20001  Witnessing the devastation caused by the powerful hurricane in the Caribbean region. Praying for the safety and well-being of all those affected. #hurricane #Caribbean   
20004                                       Devastated by the forest fire near La Ronge, Sask. My heart goes out to all affected by this tragic disaster. #LaRonge #ForestFire   
20005      Breaking news: Authorities urging locals to 'shelter in place' as wildfires continue to ravage parts of California. Stay safe and be prepared. #CaliforniaWildfires   
20006                             Massive flooding forces 10,000 residents to evacuate in Louisiana. Rescue efforts underway as homes are submerged in water. #LouisianaFloods   
20007                                           Just received this video from Emma in #California as flood waters engulf a neighborhood. Stay safe everyone! #disastercoverage   

       target  
id             
20001       1  
20004       1  
20005       1  
20006       1  
20007       1

In [9]:
import numpy as np
import projtools as pt

v1 = np.array([1.1, 2.2, 3.3])
v2 = np.array([4.4, 5.5, 6.6])
v3 = np.array([7.7, 8.8, 9.9])

v = np.hstack((v1, v2))
print(v)
v = np.hstack((v, v3))
print(v)

[1.1 2.2 3.3 4.4 5.5 6.6]
[1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9]


In [10]:
v_list = [v1, v2, v3]
v_matrix = np.vstack((v1, v2))
v_matrix = np.vstack((v_matrix, v3))
v_matrix  # stack each vector UNDER the last

array([[1.1, 2.2, 3.3],
       [4.4, 5.5, 6.6],
       [7.7, 8.8, 9.9]])

In [11]:
v_matrix2 = pt.make_tweet_feats(v_list)
v_matrix2

array([[1.1, 2.2, 3.3],
       [4.4, 5.5, 6.6],
       [7.7, 8.8, 9.9]])

In [1]:
not_stops = {"you", "on", "not", "from", "was", "but", "your", "all", "no",
                 "when", "now", "more", "over", "some", "first", "full", "down",
                 "may", "only", "last", "many", "never", "any", "everyone",
                 "every", "before", "under", "top", "most", "during", "next",
                 "while", "call", "very", "nothing", "anything", "everything",
                 "sometimes", "serious", "everywhere", "none", "except",
                 "within", "above", "below", "nobody", "afterwards", "anywhere"}
len(not_stops)

48

In [2]:
import numpy as np
import pandas as pd
import random
# https://stackoverflow.com/questions/78286353/writing-a-pandas-dataframe-with-large-vector-column?noredirect=1#comment138016611_78286353
# df = pd.DataFrame({'id' : range(1,7486),
#                    'text' : random.choices(['11', '22', 'some long random string', 'another string', 'one last word'],
#                                            k=7485),
#                    'text_vector' : [np.array([random.uniform(-2,2) for _ in range(1500)]) for _ in range(7485)],
#                    'target':random.choices(range(10000),k=7485) })
# df.to_csv(path_or_buf="./data/df_text_vec_truncate.csv", index=False, encoding='utf-8')

In [4]:
v = np.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7])
print(v.shape)

(7,)


In [5]:
v2 = np.reshape(v, (-1, 1))
print(v.shape, v2.shape)
v2

(7,) (7, 1)


array([[1.1],
       [2.2],
       [3.3],
       [4.4],
       [5.5],
       [6.6],
       [7.7]])

In [6]:
import torch

# t1 = torch.tensor([0.2, 0.7, 0.1])
# t1.argmax()  # tensor(1)

start=0; end=10; step=2
b = torch.arange(start, end, step)
b

tensor([0, 2, 4, 6, 8])

In [3]:
x = 7.1234567
print(f"x = {x:.2f}")

x = 7.12


In [10]:
import time
from datetime import datetime
print(time.ctime())
print(time.time())
datetime.now().strftime('%Y-%m-%d.%H.%M.%S')

Fri Apr 12 15:52:56 2024
1712958776.299947


'2024-04-12.15.52.56'

In [11]:
def return_tuple():
    return(('left', 'right'))

x, y = return_tuple()
print(f"x = {x}, y = {y}")

x = left, y = right


In [ ]:
# fix accuracy error reporting
sd1_relu = 0.07877542178298569 / 2.
sd1_sigmoid = 0.05552229291138861 / 2.
sd2_100h = 0
sd2_300h = 0