In [3]:
import torch  # missing from lecture 2
import torch.nn as nn

## Create input_tensor with three features
input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]])
print(input_tensor.shape)
input_tensor

torch.Size([1, 3])


tensor([[ 0.3471,  0.4547, -0.2356]])

In [4]:
# define a linear layer
linear_layer = nn.Linear(in_features=3, out_features=2)
output = linear_layer(input_tensor)
print(output)

tensor([[ 0.0834, -0.0894]], grad_fn=<AddmmBackward0>)


In [7]:
print(linear_layer.weight.shape)
linear_layer.weight
# Parameter containing:
# tensor([[ 0.1666,  0.4067, -0.4190],
#         [-0.1845,  0.0945, -0.2244]], requires_grad=True)

torch.Size([2, 3])


Parameter containing:
tensor([[ 0.1666,  0.4067, -0.4190],
        [-0.1845,  0.0945, -0.2244]], requires_grad=True)

In [6]:
linear_layer.bias
# Parameter containing:
# tensor([-0.2581, -0.1212], requires_grad=True)

Parameter containing:
tensor([-0.2581, -0.1212], requires_grad=True)

In [8]:
# ex 2
# Create a neural network of linear layers that takes a tensor of dimensions 1x8 as input and outputs a tensor of dimensions 1x1
# Use any output dimension for the first layer you want.
import torch
import torch.nn as nn

input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])

# Implement a small neural network with exactly two linear layers
model = nn.Sequential(nn.Linear(8, 3),  # using 3 as the output dim of the first layer, but could be anything
                      nn.Linear(3, 1)
                     )

output = model(input_tensor)
print(output)  # 1x1 output

tensor([[-1.5622]], grad_fn=<AddmmBackward0>)
