In [1]:
import torch  # missing from lecture 2
import torch.nn as nn

## Create input_tensor with three features
input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]])
print(input_tensor.shape)
input_tensor

torch.Size([1, 3])


tensor([[ 0.3471,  0.4547, -0.2356]])

In [2]:
# define a linear layer
linear_layer = nn.Linear(in_features=3, out_features=2)
output = linear_layer(input_tensor)
print(output)

tensor([[-0.6237,  0.6049]], grad_fn=<AddmmBackward0>)


In [3]:
print(linear_layer.weight.shape)
linear_layer.weight
# Parameter containing:
# tensor([[ 0.1666,  0.4067, -0.4190],
#         [-0.1845,  0.0945, -0.2244]], requires_grad=True)

torch.Size([2, 3])


Parameter containing:
tensor([[ 0.4013, -0.4596,  0.4234],
        [-0.1100,  0.5659,  0.2756]], requires_grad=True)

In [4]:
linear_layer.bias
# Parameter containing:
# tensor([-0.2581, -0.1212], requires_grad=True)

Parameter containing:
tensor([-0.4542,  0.4507], requires_grad=True)

In [5]:
# ex 2
# Create a neural network of linear layers that takes a tensor of dimensions 1x8 as input and outputs a tensor of dimensions 1x1
# Use any output dimension for the first layer you want.
input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])

# Implement a small neural network with exactly two linear layers
model = nn.Sequential(nn.Linear(8, 3),  # using 3 as the output dim of the first layer, but could be anything
                      nn.Linear(3, 1)
                     )

output = model(input_tensor)
print(output)  # 1x1 output

tensor([[-0.7038]], grad_fn=<AddmmBackward0>)


In [6]:
# sigmoid activation
input_tensor = torch.tensor([[6.0]])
sigmoid = nn.Sigmoid()
output = sigmoid(input_tensor)
output

tensor([[0.9975]])

In [7]:
# softmax for multi-dim classification
# Create an input tensor
input_tensor = torch.tensor([[4.3, 6.1, 2.3]])
# Apply softmax along the last dimension
probabilities = nn.Softmax(dim=-1)
output_tensor = probabilities(input_tensor)
print(output_tensor)

tensor([[0.1392, 0.8420, 0.0188]])


In [8]:
# Binary classification: forward pass
# Create input data of shape 5x6
input_data = torch.tensor(
[[-0.4421, 1.5207, 2.0607, -0.3647, 0.4691, 0.0946],
[-0.9155, -0.0475, -1.3645, 0.6336, -1.9520, -0.3398],
[ 0.7406, 1.6763, -0.8511, 0.2432, 0.1123, -0.0633],
[-1.6630, -0.0718, -0.1285, 0.5396, -0.0288, -0.8622],
[-0.7413, 1.7920, -0.0883, -0.6685, 0.4745, -0.4245]])

# Create binary classification model
model = nn.Sequential(
nn.Linear(6, 4), # First linear layer
nn.Linear(4, 1), # Second linear layer
nn.Sigmoid() # Sigmoid activation function
)
# Pass input data through model
output = model(input_data)
print(output)

tensor([[0.4184],
        [0.7402],
        [0.6142],
        [0.6220],
        [0.5035]], grad_fn=<SigmoidBackward0>)


In [9]:
# lecture 4 excercises
input_tensor = torch.Tensor([[3, 4, 6, 2, 3, 6, 8, 9]])

# Implement a small neural network for binary classification
model = nn.Sequential(
  nn.Linear(8, 1),
  nn.Sigmoid()
)

output = model(input_tensor)
print(output)

tensor([[0.0075]], grad_fn=<SigmoidBackward0>)


In [10]:
# Create a neural network with exactly four linear layers, which takes
# the input tensor as input, and outputs a regression value, using any
# shapes you like for the hidden layers.

input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Implement a neural network with exactly four linear layers
model = nn.Sequential(
    nn.Linear(11, 7),
    nn.Linear(7, 6),
    nn.Linear(6, 5),
    nn.Linear(5, 1)
)

output = model(input_tensor)
print(output)

tensor([[0.0024]], grad_fn=<AddmmBackward0>)


In [11]:
# A similar neural network to the one you just built is provided, containing four linear layers;
# update this network to perform a multi-class classification with four outputs.
input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Update network below to perform a multi-class classification with four labels
model = nn.Sequential(
  nn.Linear(11, 20),
  nn.Linear(20, 12),
  nn.Linear(12, 6),
  nn.Linear(6, 4), 
  nn.Softmax(dim=-1)
)

output = model(input_tensor)
print(output)

tensor([[0.1511, 0.1212, 0.2878, 0.4399]], grad_fn=<SoftmaxBackward0>)


In [12]:
# lecture 5

In [13]:
import torch.nn.functional as F
# one-hot encoding
print(F.one_hot(torch.tensor(0), num_classes = 3))
print(F.one_hot(torch.tensor(1), num_classes = 3))
print(F.one_hot(torch.tensor(2), num_classes = 3))

tensor([1, 0, 0])
tensor([0, 1, 0])
tensor([0, 0, 1])


In [14]:
from torch.nn import CrossEntropyLoss

scores = torch.tensor([[-0.1211, 0.1059]])
one_hot_target = torch.tensor([[1, 0]])
criterion = CrossEntropyLoss()
criterion(scores.double(), one_hot_target.double())

tensor(0.8131, dtype=torch.float64)

In [15]:
# try it manually, start with softmax probabilities
import numpy as np
scores = [-0.1211, 0.1059]
targets = [1, 0]
denom = np.exp(scores[0]) + np.exp(scores[1])
p0 = np.exp(scores[0]) / denom
p1 = np.exp(scores[1]) / denom
print(p0, p1)

0.443492440036494 0.5565075599635061


In [16]:
# simplified for single point, binary classification
# for the general multi-nomial version see: https://rpubs.com/mszczepaniak/classificationgoodness
cross_entropy = -(np.log(p0))
print(cross_entropy)  # very close: 0.81307

0.8130745235187279


In [17]:
# lecture 5 excercises
y = 1
num_classes = 3

# Create the one-hot encoded vector using NumPy
one_hot_numpy = np.array([0, 1, 0])

# Create the one-hot encoded vector using PyTorch
one_hot_pytorch = F.one_hot(torch.tensor(1), num_classes)
print(one_hot_numpy)
print(one_hot_pytorch)

[0 1 0]
tensor([0, 1, 0])


Start by creating a one-hot encoded vector of the ground truth label y, which is a required step to compare y with the scores predicted by your model. Next, you'll create a cross entropy loss function. Last, you'll call the loss function, which takes scores (model predictions before the final softmax function), and the one-hot encoded ground truth label, as inputs. It outputs a single float, the loss of that sample.

In [18]:
y = [2]
scores = torch.tensor([[0.1, 6.0, -2.0, 3.2]])

# Create a one-hot encoded vector of the label y
one_hot_label = F.one_hot(torch.tensor(y), num_classes = scores.shape[1])
print(one_hot_label)
# Create the cross entropy loss function
criterion = nn.CrossEntropyLoss()
# Calculate the cross entropy loss
loss = criterion(scores.double(), one_hot_label.double())
print(loss)

tensor([[0, 0, 1, 0]])
tensor(8.0619, dtype=torch.float64)


In [19]:
# lecture 6 - Backpropagation in PyTorch
# exercise 1
weight = torch.tensor([[-1.5349,  1.1395, -0.7303, -1.4280,  1.4367,  1.5740,  0.8475,  1.3379, 1.5674],
                       [ 1.1543,  1.2855,  0.5122,  0.4215,  0.4982,  1.5640, -0.9705, -0.4987, 0.6331]])
bias = torch.tensor([-0.1435,  1.6498])
preds = torch.tensor([[2.1289, 3.7059]])
target = torch.tensor([[1., 0.]])

In [21]:
criterion = nn.CrossEntropyLoss()

# Calculate the loss
loss = criterion(preds, target)

# Compute the gradients of the loss
# torch.set_grad_enabled(True)  # Context-manager 
loss.requires_grad = True
# loss.retain_grad()
loss.backward()

# Display gradients of the weight and bias tensors in order
print(weight.grad)
print(bias.grad)

None
None


This is the output I get in the DataCamp environment:

`tensor([[-0.5063, -0.4353, -0.3859, -0.3938, -0.5257, -0.1628, -0.5167, -0.4315,
         -0.6264],
        [ 0.5063,  0.4353,  0.3859,  0.3938,  0.5257,  0.1628,  0.5167,  0.4315,
          0.6264]])
tensor([-0.8288,  0.8288])

<script.py> output:
    tensor([[-0.5215, -0.4484, -0.3975, -0.4056, -0.5416, -0.1677, -0.5322, -0.4444,
             -0.6453],
            [ 0.5215,  0.4484,  0.3975,  0.4056,  0.5416,  0.1677,  0.5322,  0.4444,
              0.6453]])
    tensor([-0.8537,  0.8537])`
`

In [22]:
model = nn.Sequential(nn.Linear(16, 8),
                      nn.Sigmoid(),
                      nn.Linear(8, 2))

# Access the weight of the first linear layer
weight_0 = model[0].weight

# Access the bias of the second linear layer
bias_1 = model[2].bias

In [27]:
model = nn.Sequential(
    nn.Linear(in_features=16, out_features=8, bias=True),
    nn.Linear(in_features=8, out_features=4, bias=True),
    nn.Linear(in_features=4, out_features=2, bias=True)
)

weight0 = model[0].weight
weight1 = model[1].weight
weight2 = model[2].weight

print(weight0)

Parameter containing:
tensor([[-0.1071,  0.2024, -0.2384, -0.0131,  0.2494, -0.1972, -0.1973, -0.2014,
         -0.2002,  0.2105, -0.1943, -0.0190, -0.2011, -0.2072,  0.1547,  0.0311],
        [ 0.0141,  0.1303,  0.1676, -0.1798, -0.1731,  0.0695, -0.1607, -0.2313,
          0.2398,  0.1843,  0.0763, -0.2182,  0.1072,  0.0588,  0.2093, -0.2236],
        [ 0.0103, -0.1128, -0.1181, -0.0694,  0.2302, -0.1433, -0.0747, -0.1812,
         -0.2022, -0.1604, -0.1837, -0.1262, -0.1441, -0.2161, -0.1814,  0.1407],
        [-0.1892,  0.0483, -0.2183, -0.2134,  0.1870,  0.1905,  0.1514, -0.2494,
         -0.2193,  0.1960, -0.1626, -0.2326, -0.2115,  0.1810,  0.2430,  0.2214],
        [-0.1015, -0.1876,  0.2387,  0.0375,  0.1484, -0.2328, -0.2265,  0.1146,
          0.1025, -0.2453,  0.2474, -0.0629,  0.1831,  0.0089, -0.2116, -0.2073],
        [ 0.1988,  0.2435,  0.0044, -0.1996, -0.1659,  0.0005, -0.1540, -0.0734,
         -0.1695, -0.2391, -0.0378, -0.0973, -0.2471,  0.2273, -0.0283, -0.0063],


In [28]:
# Access the gradients of the weight of each linear layer
grads0 = weight0.grad
grads1 = weight1.grad
grads2 = weight2.grad

print(grads0)

None


In [ ]:
# Update the weights using the learning rate and the gradients
lr = 0.001
weight0 = weight0 - (lr * grads0)
weight1 = weight1 - (lr * grads1)
weight2 = weight2 - (lr * grads2)

TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

In [31]:
import torch.optim as optim

# Create the optimizer
optimizer = optim.SGD(model.parameters(), lr=0.001)
criterion = CrossEntropyLoss()

pred = torch.tensor([[-0.1738,  0.1308]])
target = torch.tensor([[1., 0.]])

loss = criterion(pred, target)
loss.backward()   # RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

# Update the model's parameters using the optimizer
optimizer.step()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [32]:
# lecture 7 exercises
y_hat = np.array(10)
y = np.array(1)

# Calculate the MSELoss using NumPy
mse_numpy = np.mean((y_hat - y)**2)

# Create the MSELoss function
criterion = nn.MSELoss()

# Calculate the MSELoss using the created loss function
mse_pytorch = criterion(torch.tensor(y_hat).float(), torch.tensor(y).float())
print(mse_pytorch)

tensor(81.)


In [34]:
model = nn.Sequential(
    nn.Linear(in_features=4, out_features=2, bias=True),
    nn.Sigmoid(),
    nn.Linear(in_features=2, out_features=1, bias=True)
)

criterion = nn.MSELoss()

In [ ]:
def show_results(model, dataloader):
    model.eval()
    iter_loader = iter(dataloader)
    for _ in range(3):
        feature, target = next(iter_loader)
        preds = model(feature)
        for p, t in zip(preds, target):
            print(f'Ground truth salary: {t.item():.3f}. Predicted salary: {p.item():.3f}.')

In [ ]:
# need to load data for this to work locally
num_epochs = 10
# Loop over the number of epochs and the dataloader
for i in range(num_epochs):
  for data in dataloader:
    # Set the gradients to zero
    optimizer.zero_grad()
    # Run a forward pass
    feature, target = data
    prediction = model(feature)
    # Calculate the loss
    loss = criterion(prediction, target)
    # Compute the gradients
    loss.backward()
    # Update the model's parameters
    optimizer.step()

show_results(model, dataloader)