In [1]:
import torch  # missing from lecture 2
import torch.nn as nn

## Create input_tensor with three features
input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]])
print(input_tensor.shape)
input_tensor

torch.Size([1, 3])


tensor([[ 0.3471,  0.4547, -0.2356]])

In [2]:
# define a linear layer
linear_layer = nn.Linear(in_features=3, out_features=2)
output = linear_layer(input_tensor)
print(output)

tensor([[0.3941, 0.4869]], grad_fn=<AddmmBackward0>)


In [3]:
print(linear_layer.weight.shape)
linear_layer.weight
# Parameter containing:
# tensor([[ 0.1666,  0.4067, -0.4190],
#         [-0.1845,  0.0945, -0.2244]], requires_grad=True)

torch.Size([2, 3])


Parameter containing:
tensor([[ 0.3386, -0.1939, -0.3598],
        [-0.0061, -0.1621, -0.1979]], requires_grad=True)

In [4]:
linear_layer.bias
# Parameter containing:
# tensor([-0.2581, -0.1212], requires_grad=True)

Parameter containing:
tensor([0.2799, 0.5161], requires_grad=True)

In [5]:
# ex 2
# Create a neural network of linear layers that takes a tensor of dimensions 1x8 as input and outputs a tensor of dimensions 1x1
# Use any output dimension for the first layer you want.
input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])

# Implement a small neural network with exactly two linear layers
model = nn.Sequential(nn.Linear(8, 3),  # using 3 as the output dim of the first layer, but could be anything
                      nn.Linear(3, 1)
                     )

output = model(input_tensor)
print(output)  # 1x1 output

tensor([[-4.9219]], grad_fn=<AddmmBackward0>)


In [7]:
# sigmoid activation
input_tensor = torch.tensor([[6.0]])
sigmoid = nn.Sigmoid()
output = sigmoid(input_tensor)
output

tensor([[0.9975]])

In [8]:
# softmax for multi-dim classification
# Create an input tensor
input_tensor = torch.tensor([[4.3, 6.1, 2.3]])
# Apply softmax along the last dimension
probabilities = nn.Softmax(dim=-1)
output_tensor = probabilities(input_tensor)
print(output_tensor)

tensor([[0.1392, 0.8420, 0.0188]])


In [10]:
# Binary classification: forward pass
# Create input data of shape 5x6
input_data = torch.tensor(
[[-0.4421, 1.5207, 2.0607, -0.3647, 0.4691, 0.0946],
[-0.9155, -0.0475, -1.3645, 0.6336, -1.9520, -0.3398],
[ 0.7406, 1.6763, -0.8511, 0.2432, 0.1123, -0.0633],
[-1.6630, -0.0718, -0.1285, 0.5396, -0.0288, -0.8622],
[-0.7413, 1.7920, -0.0883, -0.6685, 0.4745, -0.4245]])

# Create binary classification model
model = nn.Sequential(
nn.Linear(6, 4), # First linear layer
nn.Linear(4, 1), # Second linear layer
nn.Sigmoid() # Sigmoid activation function
)
# Pass input data through model
output = model(input_data)
print(output)

tensor([[0.4846],
        [0.6361],
        [0.6399],
        [0.5324],
        [0.6790]], grad_fn=<SigmoidBackward0>)


In [11]:
# lecture 4 excercises
input_tensor = torch.Tensor([[3, 4, 6, 2, 3, 6, 8, 9]])

# Implement a small neural network for binary classification
model = nn.Sequential(
  nn.Linear(8, 1),
  nn.Sigmoid()
)

output = model(input_tensor)
print(output)

tensor([[0.3393]], grad_fn=<SigmoidBackward0>)


In [12]:
# Create a neural network with exactly four linear layers, which takes
# the input tensor as input, and outputs a regression value, using any
# shapes you like for the hidden layers.

input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Implement a neural network with exactly four linear layers
model = nn.Sequential(
    nn.Linear(11, 7),
    nn.Linear(7, 6),
    nn.Linear(6, 5),
    nn.Linear(5, 1)
)

output = model(input_tensor)
print(output)

tensor([[-0.9025]], grad_fn=<AddmmBackward0>)


In [13]:
# A similar neural network to the one you just built is provided, containing four linear layers;
# update this network to perform a multi-class classification with four outputs.
input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Update network below to perform a multi-class classification with four labels
model = nn.Sequential(
  nn.Linear(11, 20),
  nn.Linear(20, 12),
  nn.Linear(12, 6),
  nn.Linear(6, 4), 
  nn.Softmax(dim=-1)
)

output = model(input_tensor)
print(output)

tensor([[0.1148, 0.2643, 0.2214, 0.3995]], grad_fn=<SoftmaxBackward0>)


In [ ]:
# lecture 5

In [14]:
import torch.nn.functional as F
# one-hot encoding
print(F.one_hot(torch.tensor(0), num_classes = 3))
print(F.one_hot(torch.tensor(1), num_classes = 3))
print(F.one_hot(torch.tensor(2), num_classes = 3))

tensor([1, 0, 0])
tensor([0, 1, 0])
tensor([0, 0, 1])


In [16]:
from torch.nn import CrossEntropyLoss

scores = torch.tensor([[-0.1211, 0.1059]])
one_hot_target = torch.tensor([[1, 0]])
criterion = CrossEntropyLoss()
criterion(scores.double(), one_hot_target.double())

tensor(0.8131, dtype=torch.float64)

In [18]:
# try it manually, start with softmax probabilities
import numpy as np
scores = [-0.1211, 0.1059]
targets = [1, 0]
denom = np.exp(scores[0]) + np.exp(scores[1])
p0 = np.exp(scores[0]) / denom
p1 = np.exp(scores[1]) / denom
print(p0, p1)

0.443492440036494 0.5565075599635061


In [19]:
# simplified for single point, binary classification
# for the general multi-nomial version see: https://rpubs.com/mszczepaniak/classificationgoodness
cross_entropy = -(np.log(p0))
print(cross_entropy)  # very close: 0.81307

0.8130745235187279


In [20]:
# lecture 5 excercises
y = 1
num_classes = 3

# Create the one-hot encoded vector using NumPy
one_hot_numpy = np.array([0, 1, 0])

# Create the one-hot encoded vector using PyTorch
one_hot_pytorch = F.one_hot(torch.tensor(1), num_classes)
print(one_hot_numpy)
print(one_hot_pytorch)

[0 1 0]
tensor([0, 1, 0])


Start by creating a one-hot encoded vector of the ground truth label y, which is a required step to compare y with the scores predicted by your model. Next, you'll create a cross entropy loss function. Last, you'll call the loss function, which takes scores (model predictions before the final softmax function), and the one-hot encoded ground truth label, as inputs. It outputs a single float, the loss of that sample.

In [25]:
y = [2]
scores = torch.tensor([[0.1, 6.0, -2.0, 3.2]])

# Create a one-hot encoded vector of the label y
one_hot_label = F.one_hot(torch.tensor(y), num_classes = scores.shape[1])
print(one_hot_label)
# Create the cross entropy loss function
criterion = nn.CrossEntropyLoss()
# Calculate the cross entropy loss
loss = criterion(scores.double(), one_hot_label.double())
print(loss)

tensor([[0, 0, 1, 0]])
tensor(8.0619, dtype=torch.float64)


In [ ]:
# lecture 6
